### ISSUE TITLE
Page doesn't load

### ISSUE THREAD

**Issue by anthonymonori** [Skyscanner/skyscanner.github.io#25]
As of 19/09/2023 the page doesn't load and the following is printed in the console:

```
Portal.js:3 Uncaught ReferenceError: exports is not defined
    at Module.<anonymous> (Portal.js:3:23)
    at n (bootstrap:19:22)
    at Object.<anonymous> (index.js:68:38)
    at n (bootstrap:19:22)
    at Module.<anonymous> (main.825a6638.js:2:323345)
    at n (bootstrap:19:22)
    at bootstrap:83:10
    at main.825a6638.js:2:916
(anonymous) @ Portal.js:3
n @ bootstrap:19
(anonymous) @ index.js:68
n @ bootstrap:19
(anonymous) @ main.825a6638.js:2
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.825a6638.js:2
```

**Comment by olliecurtis** [comment]
Hey @anthonymonori 👋 Thanks for raising will take a look into this asap!

**Comment by olliecurtis** [comment]
We are back up and running so will close this issue!

Thanks again for raising :)
